### PR TITLE
Rebase CoreOS 1.7.1 branch onto 1.8.1

### PR DESCRIPTION
**Pull request by marineam**
Looks like nearly everything we had in the 1.7.1 branch is in 1.8.1 except for one Go 1.5 fix.

### CODE REVIEW

**Comment by philips** [comment]
What is the upstream issue keeping this from being merged?

**Comment by marineam** [comment]
It _is_ upstream, just post 1.8.1 which was released a while ago.

**Comment by mischief** [comment]
lgtm

**Comment by vcaputo** [comment]
lgtm

**Pull request merged**
